/*jshint esversion: 6 */
export const GET_CONFIGURATION_SUCCESS = 'GET_CONFIGURATION_SUCCESS';
export const GET_CONFIGURATION_FAILED = 'GET_CONFIGURATION_FAILED';
export const GET_CONFIGURATION_REQUEST = 'GET_CONFIGURATION_REQUEST';
