/*jshint esversion: 6 */
export const GET_FINGER_SEARCH_SUCCESS = 'GET_FINGER_SEARCH_SUCCESS';
export const GET_FINGER_SEARCH_FAILED = 'GET_FINGER_SEARCH_FAILED';
export const GET_FINGER_SEARCH_REQUEST = 'GET_FINGER_SEARCH_REQUEST';
