export const GET_SEARCH_GROUP_SUCCESS = 'GET_SEARCH_GROUP_SUCCESS';
export const GET_SEARCH_GROUP_FAILED = 'GET_SEARCH_GROUP_FAILED';
export const GET_SEARCH_GROUP_REQUEST = 'GET_SEARCH_GROUP_REQUEST';
